services:
    # Laravel
    laravel:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    # Nginx
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - laravel

    # Redis
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

    # PostgreSQL
    pgsql:
        image: postgres:15
        ports:
            - 5432:5432
        volumes:
            - .docker/db/data:/var/lib/postgresql15/data
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        depends_on:
            - pgsql
